num_steps: 1000

training:
  game_variant: "2v2"

  replay_capacity: 50000
  min_buffer_size: 20000
  train_batch_size: 16384
  train_steps_per_collect: 0.041
  model_swap_interval: 100
  checkpoint_interval: 1000
  max_checkpoints: 2

  td_mode: td0
  td_lambda: 0.95

  initial_temperature: 1.0
  min_temperature: 0.1
  temperature_decay: 0.9999426
  temperature_decay_start_step: 0
  temperature_decay_start_value: 0
  initial_epsilon: 0

  eval_interval: 1000
  eval_games: 500

  checkpoint_dir: checkpoints/2v2/test_timing3
  log_dir: ./logs/2v2/test_timing3
  log_path: ./logs/2v2/test_timing3/training_log.csv
  debug_mode: true

  initial_heuristic_weight: 1.0
  heuristic_decay_steps: 25000
  logs_on_start: false

  use_duel_margin_maximization: false
  duel_margin_maximization_scale: 10000
  use_pbrs: false
  pbrs_upper_reward: 0.1
  pbrs_clean_reward: 0.2

  self_play:
    max_inference_batch: 4096
    min_games_per_batch: 2
    batch_timeout_ms: 5
    num_workers: 20
    num_games: 2048
    num_coordinators: 5
    debug_mode: true

  model:
    input_size: 2126
    hidden_layers: 3
    hidden_width: 512
    learning_rate: 0.00045
    output_activation: sigmoid
    loss_function: bce
    architecture: mlp
    debug_mode: true
