num_steps: 10000

training:
  replay_capacity: 1000000       # Shrunk from 10M to fit purely in fast RAM
  min_buffer_size: 200000        
  train_batch_size: 2048
  model_swap_interval: 100
  checkpoint_interval: 10000
  max_checkpoints: 2
  
  td_mode: mc
  td_lambda: 0.8
  
  initial_temperature: 1.0
  min_temperature: 0.1
  temperature_decay: 0.99994245     # Adjusted for 40k steps
  
  eval_interval: 10000
  eval_games: 500
  
  checkpoint_dir: checkpoints/ab_control4
  log_dir: ./logs/ab_control4
  log_path: ./logs/ab_control4/training_log.csv
  
  self_play:
    max_inference_batch: 4096     # Uncapped timeout!
    min_games_per_batch: 2
    batch_timeout_ms: 5
    num_workers: 40
    num_games: 4096              # Uncapped queue!
    
  model:
    input_size: 809
    hidden_layers: 3
    hidden_width: 256
    learning_rate: 0.0005
    debug_mode: true,
    debug_log_path: "./logs/ab_control4/debug_batch.log"





    